<?php
define('SERVER_RESPONSE_HEADER','WiChatSR');

define('ACCOUNT_SCOMM_ACTION_NONE',0);
define('ACCOUNT_SCOMM_ACTION_GET_ID_STATE',1);
define('ACCOUNT_SCOMM_ACTION_GET_ID_KEY',2);
define('ACCOUNT_SCOMM_ACTION_CHECK_GROUP_MEMBER',3);

define('ACCOUNT_SCOMM_RESPONSE_NONE',0);
define('ACCOUNT_SCOMM_RESPONSE_TRUE',1);
define('ACCOUNT_SCOMM_RESPONSE_FALSE',2);

define('ACCOUNT_SCOMM_KEY','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
?>
