<?php
define('SERVER_RESPONSE_HEADER','WiChatSR');
define('SERVER_RESPONSE_HEADER_LEN','8');

define('ACCOUNT_SCOMM_ACTION_NONE',0);
define('ACCOUNT_SCOMM_ACTION_GET_ID_STATE',1);
define('ACCOUNT_SCOMM_ACTION_GET_ID_KEY',2);

define('ACCOUNT_SCOMM_KEY','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'); 
?>